
version: 2.1
browser-tools: circleci/browser-tools@x.y

jobs:
  build:
   docker:
      - image: cimg/node:13.12-browsers
   steps:
      - checkout
      - run:
          name: "build"
          command: npm install
      - save_cache:
          paths:
            - "/src/node_module"
          key: "npm-packages"
  test:
    docker:
      - image: cimg/node:13.12-browsers
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: "test"
          command: |
            npm i
            npm run test
  audit:
    docker:
      - image: cimg/node:13.12-browsers
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: "audit"
          command: npm run audit
workflows:
  build-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - audit:
          requires:
            - test
