version: 2.1
jobs:
  build:
   docker:
      - image: circleci/node:14.15.4
   steps:
      - checkout
      - run:
          name: "build"
          command: npm install
      - save_cache:
          paths:
            - "/src/node_module"
          key: "npm-packages"
  npm version:
   docker:
      - image: circleci/node:14.15.4
   steps:
      - checkout
      - run:
          name: "npm version "
          command: npm -v
  test:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: "test"
          command: |
            npm i
            npm run test:ci
  audit:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: "audit"
          command: npm run audit
workflows:
  build-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - audit:
          requires:
            - test
