version: 2.1
job_defaults: &job_defaults
  docker:
  - image: circleci/node:14.15.4
    environment:
      CHROME_BIN: /usr/bin/google-chrome karma start --single-run
  working_directory: ~/cg-front-end
cache_key: &cache_key cg-front-end-{{ .Branch }}
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  chrome_version:
   <<: *job_defaults
   steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: "chrome_version"
          command: |
            google-chrome --version
  build:
   <<: *job_defaults
   steps:
      - checkout
      - run:
          name: "build"
          command: |
            npm i
            
      - save_cache:
          paths:
            - node_modules
          key: *cache_key
  test:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: "test"
          command: |
           npm i
           npm run test:ci
           

  create_infrastructure:
    docker:
        - image: amazon/aws-cli
    steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
workflows:
  build-workflow:
    jobs:
      - chrome_version
      - build
      - create_infrastructure

